### ISSUE TITLE
Not able to generate serial numbers as per documentation

### ISSUE THREAD

**Issue by gauravr7** [khalilmansouri/mongoose-serial#17]
Can you please elaborate the documentation.

**Comment by amustaque97** [comment]
Hi @gauravr7 can you please share what issue are u facing??

**Comment by hamudeshahin** [comment]
@amustaque97  the error is : TypeError: Cannot read properties of undefined (reading 'split')

**Comment by amustaque97** [comment]
Hi @hamudeshahin, thanks for reaching out. I'm assuming the error is coming from here:

https://github.com/khalilmansouri/mongoose-serial/blob/master/src/index.ts#L47-L71

Because of the `lastDoc` variable here:
https://github.com/khalilmansouri/mongoose-serial/blob/master/src/index.ts#L98-L100


I will take a closer look at this later in the day and try to update the issue. It would be great if you could share some more info like: does your MongoDB has any existing data? What configuration object do you pass to the plugin?


Thank you

**Comment by hamudeshahin** [comment]
Hi!. Thanks for your replay.
My model is like this:
`const mongoose = require("mongoose");
const mongooseSerial = require("mongoose-serial");

const { Schema } = mongoose;

const adSchema = new Schema(
  {
    publisher: {
      type: Schema.Types.ObjectId,
      ref: "user",
    },
    serialNumber: String,
    category: [
      {
        type: Schema.Types.ObjectId,
        ref: "category",
      },
    ],
    title_tr: {
      type: String,
    },
    title_en: {
      type: String,
    },
    title_ar: {
      type: String,
    },
    description_tr: {
      type: String,
    },
    description_ar: {
      type: String,
    },
    description_en: {
      type: String,
    },
    primaryImage: {
      type: String,
      required: [true, "Please upload primary image"],
    },
    productImage: {
      type: String,
      required: [true, "Please upload product image"],
    },
    video: {
      type: String,
    },
    image1: {
      type: String,
      required: [true, "Please upload first image"],
    },
    image2: {
      type: String,
      required: [true, "Please upload second image"],
    },
    image3: {
      type: String,
      required: [true, "Please upload thrid image"],
    },
    active: {
      type: Boolean,
      default: false,
    },
    adjects: [
      {
        adj_tr: String,
        adj_en: String,
        adj_ar: String,
        adj_value: Array,
      },
    ],
  },
  {
    timestamps: true,
  }
);

const Ad = mongoose.model("ad", adSchema);
// set mongoose serial to ad
adSchema.plugin(mongooseSerial, { filed: "serialNumber" });

module.exports = Ad;
`

i am trying to add serial number to each ad.

**Comment by amustaque97** [comment]
Hi @hamudeshahin :wave:

I'm able to generate serialNumber.  A couple of things here:
- I would request you to go through the link: https://mongoosejs.com/docs/middleware.html#defining
> Calling pre() or post() after [compiling a model](https://mongoosejs.com/docs/models.html#compiling) does not work in Mongoose in general. For example, the below pre('save') middleware will not fire.

- There is a typo in the statement: 
```javascript
adSchema.plugin(mongooseSerial, { filed: "serialNumber" });
```
here `field` keyword is written as `filed`. Please change that.

For demonstration, I'm sharing working code with minor changes like few properties I have removed from the example just for simplicity.

<details>
<summary>Click here to show code</summary>

```javascript

const mongoose = require("mongoose");
const mongooseSerial = require("mongoose-serial");

let conn = mongoose.createConnection("mongodb://localhost:9972/my_test_db", {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

console.log("DB connected successfully");

const { Schema } = mongoose;

const adSchema = new Schema(
  {
    serialNumber: String,
    title_tr: {
      type: String,
    },
    title_en: {
      type: String,
    },
    title_ar: {
      type: String,
    },
    description_tr: {
      type: String,
    },
    description_ar: {
      type: String,
    },
    description_en: {
      type: String,
    },
    primaryImage: {
      type: String,
      required: [false, "Please upload primary image"],
    },
    productImage: {
      type: String,
      required: [false, "Please upload product image"],
    },
    video: {
      type: String,
    },
    image1: {
      type: String,
      required: [false, "Please upload first image"],
    },
    image2: {
      type: String,
      required: [false, "Please upload second image"],
    },
    image3: {
      type: String,
      required: [false, "Please upload thrid image"],
    },
    active: {
      type: Boolean,
      default: false,
    },
    adjects: [
      {
        adj_tr: String,
        adj_en: String,
        adj_ar: String,
        adj_value: Array,
      },
    ],
  },
  {
    timestamps: true,
  }
);

// set mongoose serial to ad
adSchema.plugin(mongooseSerial, {
  field: "serialNumber",
});

const Ad = conn.model("ad", adSchema);

let ad1 = new Ad({ image1: "https://google.com", image2: "https://bit.ly" });
let ad2 = new Ad({ title_en: "Hello,World", active: true });

ad1.save().then(() => console.log("ad1 saved in the db"));
ad2.save().then(() => console.log("ad2 saved in the db"));

console.log("Both ads stored successfully");
```

</details>

**output**:
<img width="1792" alt="Screenshot 2022-07-21 at 9 47 31 PM" src="https://user-images.githubusercontent.com/21127788/180263681-f189e984-0627-4904-b3e9-9b03078eb468.png">

**Comment by amustaque97** [comment]
@khalilmansouri we can close this issue.

**Comment by hamudeshahin** [comment]
Oh Ok .. Thanks  😄!
