### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by ShehabSalah** [khalilmansouri/mongoose-serial#18]
I tried it but it didn't work.
So, I dropped the database the rebuilt it again and nothing changed

`let user = mongoose.model('User', UserSchema)
UserSchema.plugin(mongooseSerial, {
  field:"serialNumber",
  prefix: "ISC_",
  initCount:"yearly",
  separator: "_",
  digits: 6
})

module.exports.User = user`

**Comment by hamudeshahin** [comment]
Hi @ShehabSalah !. 
Did you fix this error ? because i have same error

**Comment by amustaque97** [comment]
Duplicate of https://github.com/khalilmansouri/mongoose-serial/issues/17

We can close this as well. @khalilmansouri
