### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by amustaque97** [khalilmansouri/mongoose-serial#19]
While I was working on issue #17, I found that NPM documentation is inappropriate. 

What is inappropriate in the documentation? Code Snippet. 

As mentioned in the official documentation of  _mongoose_ [here](https://mongoosejs.com/docs/middleware.html#defining)
> Calling pre() or post() after [compiling a model](https://mongoosejs.com/docs/models.html#compiling) does not work in Mongoose in general. For example, the below pre('save') middleware will not fire.

In our snippet we should change below code block
```javascript
let Invoice = connection.model('Invoice', invoiceSchema);
invoiceSchema.plugin(mongooseSerial, { field:"serialNumber"});
```

to this 👇
```javascript
invoiceSchema.plugin(mongooseSerial, { field:"serialNumber"});
let Invoice = connection.model('Invoice', invoiceSchema);
```

**Comment by khalilmansouri** [comment]
Thanks for the update @amustaque97  ,can I add as a maintainer?

**Comment by amustaque97** [comment]
> Thanks for the update @amustaque97 ,can I add you as a maintainer?

Yes, sure, that would be great ❤️
